### ISSUE TITLE
Currently Java 8 is not supported 

### ISSUE THREAD

**Issue by amedranogil** [universAAL/platform#10]
this is stated in https://github.com/universAAL/platform/wiki/DG-Quick-setup-and-start-guide (and other places?) and it may no longe be true!
please check

**Comment by Alfiva** [comment]
Yes, I know I wrote some of those warnings some time ago, but in fact I have been using Java 8 all along...

**Comment by amedranogil** [comment]
remember to perform a quick search to see if there are other wiki pages with this issue.
