### ISSUE TITLE
Change checkstyle criteria

### ISSUE THREAD

**Issue by cstockloew** [universAAL/platform#14]
Some of the criteria for maven-checkstyle-plugin contradict the formatting that we use. Some others IMHO do not make sense or are simply annoying. I propose to remove the following criterias:
- FileTabCharacter
- NoWhitespaceAfter
- RedundantModifier
- NeedBraces
- AvoidInlineConditionals
- HiddenField ?
- TodoComment

And change the following:
```
LineLength
<property name="max" value="120"/>
<property name="tabWidth" value="4"/>
```
```
VisibilityModifier
<property name="protectedAllowed" value="true"/>
```

Not sure about MagicNumber..

Please note, that we should actually comply with these criteras..

Links:
[current setting file](http://depot.universaal.org/Resources/Checkstyle/uaal-checkstyle-config.xml)
[explanation](http://checkstyle.sourceforge.net/checks.html)

Removing these unnecesary criterias would drastically decrease the total number of violations found and thereby making the report more useful.

**Comment by Alfiva** [comment]
Fine for me. I always found some of hese checks more annoying than helpful. I would remove magicnumber too.

**Comment by amedranogil** [comment]
I remember defining the priority of these with Dario. These should already be low priority. but if you think removing them would be more convenient, then go ahead.

**Comment by cstockloew** [comment]
done
