### ISSUE TITLE
Service Callee tutorial

### ISSUE THREAD

**Issue by ClementBrohon** [universAAL/platform#15]
```
 //Provided Service code extending service ontology and defining restrictions and profiles
 public class ProvidedService extends Lighting {
```

I have to code a provided service by ontology I want to use?

```
// Extend Lighting without an Ontology class. Use uAAL context from Activator
      OntologyManagement.getInstance().register(Activator.moduleContext,
         new SimpleOntology(MY_URI, Lighting.MY_URI, new ResourceFactory() {
         public Resource createInstance(String classURI,
         String instanceURI, int factoryIndex) {
         return new ProvidedLightingService(instanceURI);}
         }));
```
I don't understand where this part will be use? 
Wich Activator we are talking about? The main class in Karaf app? I have to serialize my service callee for an Android app, and we don't have activator class.
What is the return value? I have searched on the Lighting ontology and I haven't seen anything?

```
// Custom restriction to say it only controls light bulbs
      addRestriction(MergedRestriction.getFixedValueRestriction(LightSource.PROP_HAS_TYPE, ElectricLight.lightBulb),
         new String[] { Lighting.PROP_CONTROLS, LightSource.PROP_HAS_TYPE }, myRestrictions);
```

I haven't found the documentation about the method "addRestriction" on the javadoc. Can you send me the url please? My IDE (eclipse) can not find too.

```
 // Then define here the Service Profiles:
      // This profile is for getting all controlled lights
      ProvidedService prof1 = new ProvidedService(PROF1_GETALL);
      prof1.addOutput(OUTPUT_LAMPS, LightSource.MY_URI, 0, 0, new String[] { Lighting.PROP_CONTROLS });
      profs[0] = prof1.myProfile;
```

When I initialize a Provided Service, it will call this function who initialize a new Provided Service? I think I miss something, can you help me ?
I haven't define any function "addOutput" or "addFilteringInput" or "myProfile.addChangeEffect" in my class? 

```
//Service Callee code with the method to receive calls
 public class MyCallee extends ServiceCallee {
   // Called if a request matches a profile (find out which)
   public ServiceResponse handleCall(ServiceCall call) {
      String operation = call.getProcessURI();
      if(operation.startsWith( 
         ProvidedService. PROF2_TURNON)){
         // Profile arguments can be taken from the call
         Object input = call.getInputValue( 
            ProvidedService.INPUT_LAMP);
         // Make the light turn on here... then return success
         return new ServiceResponse(CallStatus.succeeded);
 }  }  }
```

A service Callee receives every messages on a AAl space and it is this function wich says it is treated or not?

**Comment by Alfiva** [comment]
First of all, before I try to answer your questions, please consider this: If you are not going to develop your own ontology and are just going to reuse existing ones, like ont.device, you do not have to implement any service ontology.
If this is your case, and you want to implement a Service Callee, you only need to create 1)your service profiles and 2)a ServiceCallee extension that does the handleCall()
That is, the last 2 code snippets you pasted. Let's say you will do some service with a Device. You create a Service Profile, anywhere in your code (making sure you can get it later, e.g. a static block) and put it in an array:

```
DeviceService profile1 = new DeviceService(URI_OF_PROFILE_1);
profile1.add...{use helper methods to build your profile}
...
profiles[0]=profile1.getProfile();
```

Then you make your ServiceCallee, as shown in the snippet you pasted, handling profiles accordingly. When you instantiate your ServiceCallee, you pass the profiles[] array where you put your profiles.

That is all, if you are only going to deal with, e.g. Device services, you do not need to create more classes. Please confirm if this is your situation.

**Comment by ClementBrohon** [comment]
It is my situation, so it is simpler than I expect. I try to code something to verify that I understood correctly.

`MyCallee callee=new MyCallee(moduleContext,profs);`

How I can get the moduleContext?

**Comment by Alfiva** [comment]
Just look at the Activator.start() of any example, like lighting client, for instance.
https://github.com/universAAL/samples/blob/master/lighting/client/src/main/java/org/universAAL/samples/lighting/client/Activator.java

**Comment by ClementBrohon** [comment]
I use the Alejandro's methods and code everything in the MyTest class. So I haven't the method "start()"

I can try something like "Activator.context". But I want to serialize, and in android app I will not have a Activator class, I don't know if it will works.

**Comment by Alfiva** [comment]
No, the only purpose of this mockup application is to obtain the serialization. It has nothing to do with the app you will make for Android. So just finish this app, run it in OSGi, serialize the event, profiles, etc, all you need for uAAL.xml, and then paste it into your Android app.

**Comment by ClementBrohon** [comment]
I have fixed every bug that I saw in log, but my lamp doesn't want to switch on if I send an order through universaal.

Could you confirm please that my code is correct? 

```
DeviceService profile1 = new DeviceService("http://clement.concept.org/#device_service_watch_light_change");
    	profile1.getProfile().addChangeEffect(new String[]{LightActuator.PROP_HAS_VALUE }, new Integer(100));
    	profs[0]=profile1.getProfile();
System.out.println(serialize(profile1.getProfile()));
```

I changed after the URI of my profile `_:BN000000 -> <http://clement.concept.org/#request_light>`


```
ServiceRequest req = new ServiceRequest("http://clement.concept.org/#request_light", new DeviceService(), null);
req.addChangeEffect(new String[]{LightActuator.PROP_HAS_VALUE }, new Integer(100));
System.out.println(serialize(req));
```

When I inserted the serialized code in my android code, log told me : 

![image](https://cloud.githubusercontent.com/assets/25262825/26731146/6232a942-47b3-11e7-8105-0aefb2a6d738.png)

I think it means that the caller send the message but the callee don't accept it.

**Comment by ClementBrohon** [comment]
**Service Callee**

```
<advertisement>
                <title>Turn light on</title>
                <description>SERVICE CALLEE PROFILE: Turn on a specific light source.</description>
                <action>org.universaal.nativeandroid.lightbluetooth.PUT_ON</action>
                <serialization>
                    <![CDATA[
                        @prefix ns: <http://www.daml.org/services/owl-s/1.1/Service.owl#> .
                        @prefix ns1: <http://clement.concept.org/#> .
                        @prefix ns2: <http://www.daml.org/services/owl-s/1.1/Process.owl#> .
                        @prefix ns3: <http://www.daml.org/services/owl-s/1.1/Profile.owl#> .
                        @prefix : <http://ontology.universAAL.org/Service.owl#> .

                        ns1:Profile
                            ns:presentedBy ns1:device_service_watch_light_change ;
                            a ns3:Profile ;
                            ns3:has_process ns1:device_service_watch_light_changeProcess;
                            ns3:hasResult [
                                a ns2:Result ;
                                ns2:hasEffect (
                                    [
                                        :affectedProperty [
                                            a :PropertyPath ;
                                            :thePath (
                                                <http://ontology.universAAL.org/Device.owl#hasValue>
                                            )
                                        ] ;
                                        a :ChangeEffect ;
                                        :propertyValue "100"^^<http://www.w3.org/2001/XMLSchema#int>
                                    ]
                                )
                            ] .

                        ns1:device_service_watch_light_change
                            a <http://ontology.universaal.org/PhThing.owl#DeviceService> ;
                            ns:presents ns1:Profile .

                    ]]>
                </serialization>
            </advertisement>
```



**Service Caller**

```
<requirement>
                <title>Turn light source on</title>
                <description>SERVICE CALLER REQUEST: Turn on a specific light source.</description>
                <action>org.universaal.nativeandroid.forcerUAAL.PUT_ON</action>
                <category>android.intent.category.DEFAULT</category>

                <input>
                    <key>var1</key>
                    <value>http://clement.concept.org/#input_lamp</value>
                </input>
                <serialization>
                    <![CDATA[

                    @prefix pvn: <http://ontology.universAAL.org/uAAL.owl#> .
                    @prefix ns: <http://www.daml.org/services/owl-s/1.1/Process.owl#> .
                    @prefix : <http://ontology.universAAL.org/Service.owl#> .

                    <http://clement.concept.org/#request_light>
                        a pvn:ServiceRequest ;
                        pvn:requiredResult [
                            a ns:Result ;
                            ns:hasEffect (
                                [
                                    :affectedProperty [
                                        a :PropertyPath ;
                                        :thePath (
                                            <http://ontology.universAAL.org/Device.owl#hasValue>
                                        )
                                    ] ;
                                    a :ChangeEffect ;
                                    :propertyValue "100"^^<http://www.w3.org/2001/XMLSchema#int>
                                ]
                            )
                        ] ;
                        pvn:requestedService [
                            a <http://ontology.universaal.org/PhThing.owl#DeviceService>
                        ] .

]]>
                </serialization>
            </requirement>
```

**Comment by Alfiva** [comment]
From this I assume you are testing with a client app and a server app both in Android. I haven't looked in depth but it looks like the code and serialization are fine. The log message "matching offer" means the request got to uAAL and that it has analyzed it, but there is no message about the result of the match.
I could try your serializations on my side and see if I can debug it, but I do not have much time now. For now, can you check if your intents are correctly sent/received from/to your applications? (And that they are actually running, not force-closed)

**Comment by ClementBrohon** [comment]
Edit: I have found! :)

**Comment by cstockloew** [comment]
This issue seems to be solved, I'm closing it..
