### ISSUE TITLE
Change formatter to Eclipse [built-in]

### ISSUE THREAD

**Issue by cstockloew** [universAAL/platform#16]
I personally find it very convenient to use the automatic formatter, just Ctrl-Shift-F and the code looks good. But when we use different formatters, there may be a lot of "changes" in a file that's only from formatting, mostly whitespace-changes, and then it's difficult to track what exactly has changed. Thus, we should all use the same formatter.

Currently, we use the recommendation from uaal project to use Java conventions (mostly). This has 2 drawbacks:
- You have to manually change the formatter (from default "Eclipse" to "JavaConventions") for each workspace you create, and people tend to forget this
- It has a weird way of indentation, mixing up spaces and tabs

I would like to change the formatter to the default one (Eclipse [built-in]), there are not so many differences, but this would fix the 2 issues above.

If you agree, I would go through the source and make a one-time change of formatting for all repos.

**Comment by Alfiva** [comment]
I use ctrl+shift+f all the time, so no problem from my side.

**Comment by cstockloew** [comment]
Done.
Please change your formatter to Eclipse [built-in].
