### ISSUE TITLE
Remove 'AAL'

### ISSUE THREAD

**Issue by cstockloew** [universAAL/platform#41]
As decided via mail, all occurrences of the term 'AAL' should be removed with the one exception of the organization name universAAL. This means class names, URIs, comments etc. No replacements should be given, e.g. AALSpace becomes just Space, but not uSpace.

**Comment by cstockloew** [comment]
In Eclipse, do a file search, check 'regular expression' and search for
`(?<!univers)AAL`

This should find all occurrences of 'AAL' without 'universAAL'. It's not case-sensitive, so it does not find 'universaal'...

**Comment by cstockloew** [comment]
When we get to the "higher" layers, there are more and more occurrences of 'uAAL' which may be acceptable, but they make the search more difficult. Therefore, I would like to also remove those parts, i.e.:
- Renaming the three uAAL classes in mw.container.osgi, e.g. uAALBundleContext -> BundleContext.
- Resource.uAAL_XXX, e.g. uAAL_NAMESPACE_PREFIX -> NAMESPACE_PREFIX
- org.universAAL.middleware.util.Constants, e.g.: VAR_uAAL_CURRENT_DATETIME -> VAR_CURRENT_DATETIME

OK?

**Comment by amedranogil** [comment]
[BundleContext](https://osgi.org/javadoc/r4v43/core/org/osgi/framework/BundleContext.html) is already an OSGi concept (infact the inspiration for ModuleContext :wink: )

**Comment by cstockloew** [comment]
oops, right, so we get a name clash for that. What about OSGiModuleContext (OSGiContainer, OSGiExtender)?

What about the others?

**Comment by amedranogil** [comment]
OSGiModuleContext :+1:

**Comment by cstockloew** [comment]
FYI: mw should be mostly free of 'AAL' by now, There is something left for deployment/mpa model, but the remaining instances should be handles by other issues.

**Comment by cstockloew** [comment]
done
