### ISSUE TITLE
org.ops4j.pax.scanner.ScannerException

### ISSUE THREAD

**Issue by benediktrauch** [universAAL/platform#45]
Hey there, 
we are trying to get the "Hello World" running.
Using the Eclipse SDK Version: 3.7.2, JDK 1.8 for Eclipse and 1.7 for Maven compilation. 
http://depot.universaal.org/eclipse-update/
https://github.com/universAAL/platform/wiki/Hello-World

After "Create a new uAAL Run Config" and ajusting all configurations I get the following error:
`org.ops4j.pax.scanner.ScannerException: Could not parse the provision file
`
I have no idea what to do. Can anyone help?

**Comment by Alfiva** [comment]
Personally I would suggest using Karaf for running uAAL instead of within Eclipse
quick: https://github.com/universAAL/platform/wiki/Running-with-Apache-Karaf-(Quick)
details: https://github.com/universAAL/platform/wiki/Running-with-Apache-Karaf-%28Details%29

**Comment by cstockloew** [comment]
I just uploaded a new version of the tools, please
Install Eclipse Modelling Tools version 4.6 (Neon)
Install Eclipse Plugins from http://depot.universaal.org/eclipse-update/4.6/
