### ISSUE TITLE
org.ops4j.pax.runner.platform.PlatformException: [link:classpath:runner-links/org.apache.felix.gogo.command-0.12.0.link] is not a valid bundle

### ISSUE THREAD

**Issue by e8859487** [universAAL/platform#5]
I'm new to universAAL and follow the tutorial to learn the platform from [here](https://github.com/universAAL/platform/wiki/RD-Hello-World). 

It pretty frustrated me to print a "Hello World"

When I run the program in eclipse, it  keep shows error "org.ops4j.pax.runner.platform.PlatformException: [link:classpath:runner-links/org.apache.felix.gogo.command-0.12.0.link] is not a valid bundle" .

I have been stuck here for several days. Is there any way can solve it?

**Comment by cstockloew** [comment]
The gogo shell was introduced as default shell as of felix version 3.0.0.
Please go to your run config and open the tab "bundles". Make sure, that no bundle is selected and that the framework is set to "Felix 2.0.1 via Pax Runner".

**Comment by e8859487** [comment]
Here is the new issue 　
org.ops4j.pax.runner.platform.PlatformException: [link:classpath:runner-links/org.apache.felix.shell.tui-1.4.1.link] is not a valid bundle.

The problem is same as [here](http://forge.universaal.org/gf/project/support/forum/?_forum_action=MessageReply&message_id=1274&action=ForumBrowse)

I have checked the Framework is Felix 2.0.1 via Pax Runner and non of bundles were selected.

thank for your help.

**Comment by Alfiva** [comment]
Alternatively you may want to read these instructions on running universAAL in Karaf: https://github.com/universAAL/platform/wiki/DG-Quick-setup-and-start-guide#Setup_build_run_and_debug_in_OSGI . If you have developed the hello world already you can keep doing so as before, just following the instructions for running (and debugging) from that link instead.

**Comment by amedranogil** [comment]
A bit going into the issue it self, to me it seems that one (or more) of the bundles provided by the default composite (whether it is the middleware build or the eclipse plugin is beyond me) is no longer available in the maven central repository. 
To check, we need the list of bundles, and go one by one searching in maven central to check if the referenced version of every artifact is accessible. This might also explain why it does work locally, we as long time developers have all those versions in our local repositories and eclipse simply locates them there.
Solution a) rework the composite file to include a valid version that is in maven central
Solution b) deploy the missing artifacts in our thirdparty repo (but will require developers to include this repo in their global config).

**Comment by cstockloew** [comment]
I just uploaded a new version of the tools, please
Install Eclipse Modelling Tools version 4.6 (Neon)
Install Eclipse Plugins from http://depot.universaal.org/eclipse-update/4.6/
