### ISSUE TITLE
Substract Restriction

### ISSUE THREAD

**Issue by ivllopis** [universAAL/platform#7]
Hello there,
my name is Ivan Llopis. I am currently starting to develop applications with universAAL. Actually a complete beginner.

I have just built my first context bus applications. I was wondering how could I set a restriction that instead of forcing a certain kind of events, accepts all kind of events but one.

For instance, how to create a subscriber that accepts all kinds of Device, but the LightSensor type.

The most similar thing I've seen so far, is the Complement restriction, in: https://github.com/universAAL/platform/wiki/RD-Understanding-Ontologies#Class_Expressions.

However, I would like to see an example using it, or the proper type of restriction, if there is another one more suitable for it.

Thanks in advance,

Ivan

**Comment by amedranogil** [comment]
Hello,
[Complement](http://depot.universaal.org/Resources/app-doc/latest/org/universAAL/middleware/owl/Complement.html) is the Class expression you are looking for.
I'm sure my colleagues @universAAL/core are working right now on providing some java code for you; on the mean time please have a look at the documentation.

**Comment by saiedt** [comment]
Hi,

I can provide the solution in terms of Turtle because I am not sure 
about the syntactical details in Java:

    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @prefix : <http://www.w3.org/2002/07/owl#> .

    [ a :class ;
       # a set of context events
       rdfs:subclassOf
    <universAAL-namespace-for-ContextEvent#ContextEvent> ;
       # whose subjects are of any type other than LightSource
       rdfs:subclassOf [
         a :Restriction ;
         :onProperty <http://www.w3.org/1999/02/22-rdf-syntax-ns#subject> ;
         :allValuesFrom [
           a :Class ;
           :complementOf <namespace-for-lighting-ontology#LightSource>
         ]
       ]
    ]


Kind regards,

-- Saied

Alejandro Medrano wrote on 3.3.17 16:06:

**Comment by cstockloew** [comment]
Hi,

to have all Devices but LightSensor, you need an intersection. Thus, the subject of the context event is an intersection of Device and the complement of LightSensor.

In OWL Functional Style Syntax, it should look like this:
`ObjectAllValuesFrom(rdf:subject, ObjectIntersectionOf(Device, ObjectComplementOf(LightSensor)))`

In universAAL, it should look like this (but I haven't tested it yet):

`Intersection i = new Intersection();`
`i.addType(TypeURI.asTypeURI(Device.MY_URI));`
`i.addType(new Complement(TypeURI.asTypeURI(LightSensor.MY_URI)));`

`MergedRestriction r = MergedRestriction.getAllValuesRestriction(ContextEvent.PROP_RDF_SUBJECT, i);`

`ContextEventPattern p = new ContextEventPattern();`
`p.addRestriction(r);`

BR,
CS

**Comment by ivllopis** [comment]
Thank you so much!
I will try it in the next few days.

Kind regards,

Ivan

**Comment by ivllopis** [comment]
Amazing! It worked.
Absolutely brilliant. 

Thank you so much!

Kind regards,

Ivan
