### ISSUE TITLE
Remove uaal-maven-plugin:TestMojo from uAAL.pom

### ISSUE THREAD

**Issue by amedranogil** [universAAL/platform#9]
Not every project is using the iTests, and this mojo takes arround 5 seconds each execution.
The plugin is activated by default for all, because CompositeMojo generates composite files, which are used

Tasks:
1. Remove TestMojo from default configuration in uAAL.pom
2. check build-helper-maven-plugin to see if attaches automatically the output
2. Add TestMojo configuration to those projects that do use iTests

Idea: 
prepare different [profiles](http://maven.apache.org/guides/introduction/introduction-to-profiles.html) in uAAL.pom in function of using only composites (again not always used but activated by default) or composites + iTests. These profiles can be activated through a project property and if the output file is missing (which might save time also when developing).

**Comment by cstockloew** [comment]
Does this mean that we need to activate the profile/TestMojo manually (=change the pom) or add TestMojo config _for each project_ that uses itest? There are many projects that do use itests, and modifying all of these pom files can be a lot of work.

AFAK, if you want to use itests, you need it as direct dependency (not transitive). Is it possible to check the pom for this direct dependency and create the test composite only if this dependency exists? I guess, the pom is anyway checked to create the composite, so we can "easily" add the check...
That way, the creation of test-composites is tied to the existence of a dependency, which we already have. Otherwise, we might have to check every project again whether to set the profile/add Testmojo config (if I understood you correctly).

Task 2: it attaches composite+deps (not test-composite)

**Comment by amedranogil** [comment]
List of current projects with references to itests:
context/ctxt.che/pom.xml      
context/ctxt.che.mobile/pom.xml      
context/ctxt.prof.server/pom.xml      
context/ctxt.space.server/pom.xml      
context/ctxt.sysinfo.provider/pom.xml      
lddi/lddi.common/lddi.abstraction/pom.xml      
lddi/lddi.common/lddi.exporter.activityhub/pom.xml      
lddi/lddi.common/lddi.exporter.x73/pom.xml      
lddi/lddi.fs20/lddi.fs20.exporter/pom.xml      
lddi/lddi.knx/lddi.knx.devicemanager/pom.xml      
lddi/lddi.knx/lddi.knx.networkdriver/pom.xml      
middleware/middleware.osgi/mw.bus.context.osgi/pom.xml      
middleware/middleware.osgi/mw.bus.model.osgi/pom.xml      
middleware/middleware.osgi/mw.bus.service.osgi/pom.xml      
middleware/middleware.osgi/mw.bus.tracker.osgi/pom.xml      
middleware/middleware.osgi/mw.connectors.communication.jgroups.osgi/pom.xml      
middleware/middleware.osgi/mw.connectors.discovery.slp.osgi/pom.xml      
middleware/middleware.osgi/mw.container.osgi/pom.xml      
middleware/middleware.osgi/mw.data.representation.osgi/pom.xml      
middleware/middleware.osgi/mw.data.serialization.osgi/pom.xml      
middleware/middleware.osgi/mw.interfaces.osgi/pom.xml      
middleware/middleware.osgi/mw.managers.aalspace.osgi/pom.xml      
middleware/middleware.osgi/mw.managers.deploy.osgi/pom.xml      
middleware/middleware.osgi/mw.managers.tenant.osgi/pom.xml      
middleware/middleware.osgi/mw.pom.osgi/pom.xml        
ontology/ont.activityhub/pom.xml      
ontology/ont.av/pom.xml      
ontology/ont.che/pom.xml      
ontology/ont.continuahealthmanager/pom.xml      
ontology/ont.cryptographic/pom.xml      
ontology/ont.dependability/pom.xml      
ontology/ont.device/pom.xml      
ontology/ont.device.extra/pom.xml      
ontology/ont.furniture/pom.xml      
ontology/ont.gesture.pointing/pom.xml      
ontology/ont.health.disease/pom.xml      
ontology/ont.health.measurement/pom.xml      
ontology/ont.hvac/pom.xml      
ontology/ont.impairment/pom.xml      
ontology/ont.languages/pom.xml      
ontology/ont.lighting/pom.xml      
ontology/ont.measurement/pom.xml      
ontology/ont.multimedia/pom.xml      
ontology/ont.phWorld/pom.xml      
ontology/ont.pom/composite/pom.xml      
ontology/ont.profile/pom.xml      
ontology/ont.profile.health/pom.xml      
ontology/ont.profile.ui.mainmenu/pom.xml      
ontology/ont.profile.ui.preferences/pom.xml      
ontology/ont.recommendations/pom.xml      
ontology/ont.security/pom.xml      
ontology/ont.sysinfo/pom.xml      
ontology/ont.unit/pom.xml      
remote/ri.api.manager/pom.xml      
remote/ri.gateway.multitenant/pom.xml      
remote/ri.rest.manager/pom.xml			
remote/ri.servicegateway/pom.xml      
security/security.authorisator/pom.xml		
service/srvc.asor/pom.xml      
ui/ui.handler.sms/pom.xml      
ui/ui.kinect.adapter/pom.xml      
ui/ui.kinect.adapter.instance/pom.xml      
ui/ui.resource.server/pom.xml      
xtras/maven/archetypes/module.generic-archetype/src/main/resources/archetype-resources/pom.xml		
xtras/samples/aapi/client-regular/pom.xml      
xtras/samples/aapi/client-simple/pom.xml      
xtras/samples/aapi/server-regular/pom.xml      
xtras/samples/aapi/server-simple/pom.xml      
xtras/samples/activityhub/client/pom.xml      
xtras/samples/activityhub/simulator/pom.xml      
xtras/samples/lighting/client/pom.xml      
xtras/samples/lighting/server/pom.xml      
xtras/samples/lighting/uiclient/pom.xml      
xtras/samples/smp.mw.broker.client/pom.xml

**Comment by amedranogil** [comment]
The Real problem is that in most of the projects the reference in the pom is there for, you could say, tradition; but in reality there is no integration test that actually implement a iTest, so that is another thing to look out for.

**Comment by amedranogil** [comment]
List of current itest implementations:
context/ctxt.che/src/test/java/org/universAAL/context/che/ArtifactIT.java
context/ctxt.che.mobile/src/test/java/org/universAAL/context/chemobile/test/ArtifactIT.java
context/ctxt.prof.server/src/test/java/org/universAAL/context/prof/serv/ArtifactIT.java
context/ctxt.space.server/src/test/java/org/universAAL/context/space/serv/ArtifactIT.java
middleware/middleware.osgi/mw.bus.context.osgi/src/test/java/org/universAAL/middleware/context/test/ArtifactIT.java
middleware/middleware.osgi/mw.bus.context.osgi/src/test/java/org/universAAL/middleware/context/test/SerializerIT.java
middleware/middleware.osgi/mw.bus.model.osgi/src/test/java/org/universAAL/middleware/bus/model/test/ArtifactIT.java
middleware/middleware.osgi/mw.bus.service.osgi/src/test/java/org/universAAL/middleware/service/test/ArtifactIT.java
middleware/middleware.osgi/mw.bus.tracker.osgi/src/test/java/org/universAAL/middleware/gateway/test/BusRegistryIT.java
middleware/middleware.osgi/mw.connectors.communication.jgroups.osgi/src/test/java/org/universAAL/middleware/connectors/communication/jgroups/test/ArtifactIT.java
middleware/middleware.osgi/mw.connectors.discovery.slp.osgi/src/test/java/org/universAAL/middleware/connectors/discovery/slp/test/ArtifactIT.java
middleware/middleware.osgi/mw.container.osgi/src/test/java/org/universAAL/middleware/container/test/ArtifactIT.java
middleware/middleware.osgi/mw.data.representation.osgi/src/test/java/org/universAAL/middleware/datarep/test/ArtifactIT.java
middleware/middleware.osgi/mw.data.serialization.osgi/src/test/java/org/universAAL/serialization/test/ArtifactIT.java
middleware/middleware.osgi/mw.managers.aalspace.osgi/src/test/java/org/universAAL/middleware/managers/aalspace/test/ArtifactIT.java
middleware/middleware.osgi/mw.managers.deploy.osgi/src/test/java/org/universAAL/middleware/managers/deploy/test/ArtifactIT.java
ontology/ont.hvac/src/main/resources/ArtifactIntegrationTest.java
ontology/ont.hvac/target/classes/ArtifactIntegrationTest.java
ontology/ont.pom/composite/src/test/java/org/universAAL/ontology/test/ArtifactIT.java
remote/ri.api.manager/src/test/java/org/universAAL/ri/api/manager/ArtifactIT.java
remote/ri.servicegateway/src/test/java/org/universAAL/ri/servicegateway/test/ArtifactIT.java
security/security.authorisator/src/test/java/org/universAAL/security/authorisator/ArtifactIT.java
ui/ui.handler.sms/src/test/java/org/universAAL/ui/handler/sms/test/ArtifactIT.java
ui/ui.kinect.adapter/src/test/java/org/universAAL/ui/kinect/adapter/test/ArtifactIT.java
ui/ui.kinect.adapter.instance/src/test/java/org/universAAL/ui/kinect/adapter/instance/test/ArtifactIT.java
ui/ui.resource.server/src/test/java/org/universAAL/ui/resource/server/test/ArtifactIT.java
xtras/maven/archetypes/module.generic-archetype/src/main/resources/archetype-resources/src/test/java/ArtifactIT.java
xtras/samples/aapi/client-regular/src/test/java/org/universAAL/samples/lighting/client/test/LightingRegularIT.java
xtras/samples/aapi/client-simple/src/test/java/org/universAAL/samples/lighting/client/test/LightingSimpleIT.java
xtras/samples/aapi/server-simple/src/test/java/org/universAAL/samples/lighting/server/test/ArtifactIT.java
xtras/samples/lighting/client/src/test/java/org/universAAL/samples/lighting/client/test/LightingIT.java
xtras/samples/lighting/server/src/test/java/org/universAAL/samples/lighting/server/test/ArtifactIT.java
xtras/samples/smp.mw.broker.client/src/test/java/org/universAAL/middleware/broker/client/test/ArtifactIT.java

**Comment by amedranogil** [comment]
additionally some, if not most of these iTests could be ignored. Because the only test is the module actually starting correctly in osgi, and this can be tested for the whole repo in the respective composite.

**Comment by amedranogil** [comment]
Projects where the itest dependency can be (as for now) safely removed (there are no IntegrationTests) (1st listing - 2nd listing):
context/ctxt.sysinfo.provider/
lddi/lddi.common/lddi.abstraction/
lddi/lddi.common/lddi.exporter.activityhub/
lddi/lddi.common/lddi.exporter.x73/
lddi/lddi.fs20/lddi.fs20.exporter/
lddi/lddi.knx/lddi.knx.devicemanager/
lddi/lddi.knx/lddi.knx.networkdriver/
middleware/middleware.osgi/mw.interfaces.osgi/
middleware/middleware.osgi/mw.managers.tenant.osgi/
middleware/middleware.osgi/mw.pom.osgi/
ontology/ont.activityhub/
ontology/ont.av/
ontology/ont.che/
ontology/ont.continuahealthmanager/
ontology/ont.cryptographic/
ontology/ont.dependability/
ontology/ont.device.extra/
ontology/ont.device/
ontology/ont.furniture/
ontology/ont.gesture.pointing/
ontology/ont.health.disease/
ontology/ont.health.measurement/
ontology/ont.hvac/
ontology/ont.impairment/
ontology/ont.languages/
ontology/ont.lighting/
ontology/ont.measurement/
ontology/ont.multimedia/
ontology/ont.phWorld/
ontology/ont.profile.health/
ontology/ont.profile.ui.mainmenu/
ontology/ont.profile.ui.preferences/
ontology/ont.profile/
ontology/ont.recommendations/
ontology/ont.security/
ontology/ont.sysinfo/
ontology/ont.unit/
remote/ri.gateway.multitenant/
remote/ri.rest.manager/
service/srvc.asor/
xtras/samples/aapi/server-regular/
xtras/samples/activityhub/client/
xtras/samples/activityhub/simulator/
xtras/samples/lighting/uiclient/

**Comment by cstockloew** [comment]
thanks for the info, to have the numbers written down (without duplicates):
74 projects with itests dependency
29 projects with itest implementations
266 projects in total
(If we assume 5 sec, this takes ~20 min for unnecessary itest generation)

I agree that we should re-check and remove the itests if there is no actual implementation.

However, how do we proceed?
Can we go for a solution that does not need any additional configuration or profile setting for each project, but only the direct dependency to itests?

BTW: ontology/ont.hvac/ has an IT in src/main/resources. Is this intended?

**Comment by amedranogil** [comment]
Configuration would only be necesary for the 29 projects that actually use the itests; which again may be less as most can be removed and bunched into the composite project (takes the same to calculate dependencies for a single project than for all projects in a repo).

I still think the best option is to create a special profile for itest usage (maybe leave the composite generation for all). the problem is how we activate this profile, more or less automatically...

I'm thinking on creating a mojo in uAALDirectives maven plugin to solve this. The mojo will check if the itest dependency is declared, and if there is an actual IntegrationTest, removing the dependency if the second case in nor met, and adding a property to activate the profile if both cases are met.

**Comment by amedranogil** [comment]
> Can we go for a solution that does not need any additional configuration or profile setting for each project, but only the direct dependency to itests

A solution for this would be similar to what we have done for OntTestCase; but harder... the problem is that the mojo does have access to the pom and thus to the dependency tree, as well as all the maven functions to resolve such dependency tree. The test does not. 
Also remember there is a profile you can use for personalized itest runtime environment which is taken into account in the mojo, which is also very hard to process from the test.

**Comment by cstockloew** [comment]
I'm not thinking about a u-test. My proposal is to modify uaal-maven-plugin/UaalTestMojo.java to check for the direct dependency of itests. Then, all you need to do to have an itest, is the integration of that dependency. No further config is required.

If there is a dependency to itests and you want to skip itests-composite generation, then you can already use -DskipTests. This will not only skip the tests but also the itests-composite generation. This is already implemented.

**Comment by amedranogil** [comment]
I'm dense! that is genius!
I had already finished my idea, so I do have a check for implementation of IntegrationTests. It is a matter of adding this condition to the mojo! 
EASY!

**Comment by amedranogil** [comment]
Please verify all the changes don't break anything (*), and in fact are in effect (not generating test-composite when not needed) before closing.

(*) right now some ontologies fail because they have sintactic issues and need to be fixed.

**Comment by cstockloew** [comment]
so far, no poblems. But I only worked on ontologies (*)

(*) which should work again.

**Comment by cstockloew** [comment]
No problem so far, I'm closing this issue.
